---
# file: foundation-ubuntu.yml

- hosts: 127.0.0.1
  connection: local
  become: yes
  tasks:
  - name: ensure OpenVPN repository is enabled
    apt_repository:
      repo: deb http://swupdate.openvpn.net/apt trusty main
      state: present
  - name: ensure OpenVPN repository key is present
    apt_key:
      url: https://swupdate.openvpn.net/repos/repo-public.gpg
      state: present
  - name: ensure OpenVPN server is installed
    apt:
      update_cache: yes
      name: openvpn
      state: latest
  roles:
  - role: cloudwatch
    logs:
    - file: /var/log/syslog
      format: "%b %d %H:%M:%S"
      group_name: openvpn
      stream_name: "{instance_id}-syslog"
    - file: /var/log/kern.log
      format: "%b %d %H:%M:%S"
      group_name: openvpn
      stream_name: "{instance_id}-kern.log"
    - file: /var/log/openvpn.log
      format: "%a %b %d %H:%M:%S %Y"
      group_name: openvpn
      stream_name: "{instance_id}-kern.log"
  - cloud-init